### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by migo256** [Link009/LPEX#2]
python3.5 Extraction.py -i IMG_9005.JPG 
Traceback (most recent call last):
  File "Extraction.py", line 57, in <module>
    contours, hierarchy = cv2.findContours(thresh, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

**Comment by Link009** [comment]
Hi

If you open the code, at line 52 you can see that for OpenCV 3.4 (or less), you have to set 3 variables for cv2.findContours.
You have to edit the code at that line.

**Comment by migo256** [comment]
Thank you!

Hint: you may check the version of cv2 via:
print(cv2.__version__)

**Comment by migo256** [comment]
`print(cv2.__version__)`

**Comment by Link009** [comment]
Updated code.
