### ISSUE TITLE
only part of the plate is detected

### ISSUE THREAD

**Issue by moxgeek** [Link009/LPEX#4]
hello 
i see that the code works very well and i thank you for that 
however , while testing it to some " moroccan car " , the things went wrong 
it's shows only part of the plate
<img src="https://ak7.picdn.net/shutterstock/videos/1022314897/thumb/1.jpg" style="width:200px;height:200px;">
result 
<a href="https://imgbb.com/"><img src="https://i.ibb.co/PcbdqB5/inmg.png" alt="inmg" border="0"></a>
and 
<img src="https://i.ytimg.com/vi/4sJSgE3ib7U/maxresdefault.jpg" style="width:200px;height:200px;">

<img src="https://i.ibb.co/G51DG56/inmg.png" alt="inmg" border="0">

what i can do in this case ?

**Comment by Link009** [comment]
Hi

I suggest you to do some kind of preprocessing first. 

What worked for me, for the first image, was to change it's resolution; open the image with Paint and change width to 1200 pixels (height will change automatically). Save and execute script again.

![immagine](https://user-images.githubusercontent.com/12837329/63895012-52333d80-c9ee-11e9-9aa2-4c3b43091520.png)

For the second image, the procedure above seems to not have effect. I obtain the same result as you. In my opinion the script output here is right. If you understand how the program works, you must understand also why it doesn't recognize the whole plate: it search for alpha-numeric components. Obviously the last digit (1) seems to be too far/it's not recognized so it's being leaved alone.

You could play with values at lines 195-205 (today version of code - it can change in the future). This is useful only if you have images of the same size and plates in more or less the same distance.
